# Generated by Django 5.2.12 on 2026-08-25 01:20

import apps.reservations.models
import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('reservations', '0001_enable_btree_gist'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(editable=False, max_length=12, unique=True, verbose_name='código')),
                ('starts_at', models.DateTimeField(verbose_name='inicio')),
                ('ends_at', models.DateTimeField(help_text='Hora a la que se libera la mesa. Se calcula sola.', verbose_name='fin')),
                ('service_date', models.DateField(db_index=True, help_text='Día al que pertenece el servicio. Una cena que acaba pasada la medianoche sigue contando como la noche anterior.', verbose_name='fecha de servicio')),
                ('duration_min', models.PositiveSmallIntegerField(help_text='Cuánto ocupa la mesa esta reserva. Si más adelante cambias la duración estándar, esta reserva no se mueve.', verbose_name='duración (min)')),
                ('party_size', models.PositiveSmallIntegerField(verbose_name='comensales')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='niños')),
                ('high_chairs', models.PositiveSmallIntegerField(default=0, verbose_name='sillas de bebé')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de confirmar'), ('confirmed', 'Confirmada'), ('seated', 'Sentada'), ('finished', 'Finalizada'), ('waitlisted', 'En lista de espera'), ('cancelled', 'Cancelada'), ('no_show', 'No-show')], db_index=True, default='pending', max_length=12, verbose_name='estado')),
                ('source', models.CharField(choices=[('web', 'Web'), ('phone', 'Teléfono'), ('whatsapp', 'WhatsApp'), ('walk_in', 'Mostrador / walk-in'), ('staff', 'Personal')], default='web', max_length=12, verbose_name='origen')),
                ('occasion', models.CharField(blank=True, help_text='Cumpleaños, aniversario, cena de negocios... Es lo que permite el detalle que hace volver al cliente.', max_length=40, verbose_name='ocasión')),
                ('guest_notes', models.TextField(blank=True, verbose_name='notas del cliente')),
                ('internal_notes', models.TextField(blank=True, help_text='Solo lo ve el equipo. Nunca se envía en el correo de confirmación.', verbose_name='notas internas')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='monto del depósito')),
                ('deposit_status', models.CharField(choices=[('not_applicable', 'No aplica'), ('pending', 'Pendiente'), ('paid', 'Pagado'), ('refunded', 'Devuelto'), ('kept', 'Retenido')], default='not_applicable', max_length=15, verbose_name='estado del depósito')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmada en')),
                ('seated_at', models.DateTimeField(blank=True, null=True, verbose_name='sentada en')),
                ('released_at', models.DateTimeField(blank=True, null=True, verbose_name='liberada en')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelada en')),
                ('cancellation_reason', models.CharField(blank=True, max_length=120, verbose_name='motivo de cancelación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada en')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guest', verbose_name='cliente')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='venues.shift', verbose_name='turno')),
                ('tags', models.ManyToManyField(blank=True, related_name='reservations', to='guests.tag', verbose_name='etiquetas')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='venues.venue', verbose_name='restaurante')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('from_status', models.CharField(blank=True, max_length=12, verbose_name='estado anterior')),
                ('to_status', models.CharField(max_length=12, verbose_name='estado nuevo')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reservations.reservation', verbose_name='reserva')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'movimiento',
                'verbose_name_plural': 'historial de movimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('min_lead_hours', models.PositiveSmallIntegerField(default=2, help_text='Con cuánta anticipación puede reservar alguien desde la web. Por teléfono o en mostrador no se aplica.', verbose_name='antelación mínima (horas)')),
                ('max_lead_days', models.PositiveSmallIntegerField(default=60, verbose_name='antelación máxima (días)')),
                ('max_party_web', models.PositiveSmallIntegerField(default=8, help_text='A partir de aquí, el grupo tiene que llamar. Así los eventos grandes los revisa alguien.', verbose_name='máximo de comensales por web')),
                ('no_show_grace_min', models.PositiveSmallIntegerField(default=15, help_text='Minutos de cortesía antes de marcar la reserva como no-show.', verbose_name='cuánto esperas antes del no-show (min)')),
                ('overbooking_pct', models.PositiveSmallIntegerField(default=0, verbose_name='sobreventa permitida (%)')),
                ('web_auto_confirm', models.BooleanField(default=True, help_text='Si lo desmarcas, cada reserva de la web queda pendiente hasta que alguien la revise.', verbose_name='confirmar sola la reserva web')),
                ('default_duration_min', models.PositiveSmallIntegerField(default=90, help_text='Se usa cuando ningún tramo de la tabla de duraciones encaja con el grupo.', verbose_name='duración por defecto (min)')),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='venues.venue', verbose_name='restaurante')),
            ],
            options={
                'verbose_name': 'reglas de reserva',
                'verbose_name_plural': 'reglas de reserva',
            },
        ),
        migrations.CreateModel(
            name='TableOccupancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('starts_at', models.DateTimeField(verbose_name='inicio')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('is_primary', models.BooleanField(default=True, help_text='Cuando se juntan varias mesas, la principal es la que representa a la reserva en el plano.', verbose_name='principal')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Se desmarca sola al cancelar, marcar no-show o cerrar la reserva. Solo las activas ocupan la mesa.', verbose_name='activa')),
                ('block_reason', models.CharField(blank=True, max_length=120, verbose_name='motivo del bloqueo')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='asignada en')),
                ('reservation', models.ForeignKey(blank=True, help_text='Déjalo vacío si es un bloqueo de mesa (mantenimiento, evento privado) y no una reserva.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='reservations.reservation', verbose_name='reserva')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancies', to='venues.table', verbose_name='mesa')),
            ],
            options={
                'verbose_name': 'ocupación de mesa',
                'verbose_name_plural': 'ocupaciones de mesa',
                'ordering': ['starts_at', 'table__code'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateField(db_index=True, verbose_name='fecha')),
                ('desired_time', models.TimeField(verbose_name='hora deseada')),
                ('flexibility_min', models.PositiveSmallIntegerField(default=60, help_text='Cuántos minutos antes o después de esa hora le sirven al cliente.', verbose_name='flexibilidad (min)')),
                ('party_size', models.PositiveSmallIntegerField(verbose_name='comensales')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='prioridad')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='notas')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='avisado en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='guests.guest', verbose_name='cliente')),
                ('resolved_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_waitlist', to='reservations.reservation', verbose_name='resuelta con')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='venues.venue', verbose_name='restaurante')),
            ],
            options={
                'verbose_name': 'cliente en lista de espera',
                'verbose_name_plural': 'lista de espera',
                'ordering': ['date', '-priority', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['service_date', 'status'], name='reservation_day_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['starts_at'], name='reservation_start_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest', '-starts_at'], name='reservation_guest_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='reservation_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('party_size__gt', 0)), name='reservation_party_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('children__lte', models.F('party_size'))), name='reservation_children_within_party'),
        ),
        migrations.AddIndex(
            model_name='reservationevent',
            index=models.Index(fields=['reservation', '-created_at'], name='reservation_reserva_2e4099_idx'),
        ),
        migrations.AddIndex(
            model_name='tableoccupancy',
            index=models.Index(fields=['table', 'starts_at', 'ends_at'], name='occupancy_table_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='tableoccupancy',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='occupancy_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='tableoccupancy',
            constraint=models.CheckConstraint(condition=models.Q(('reservation__isnull', False), models.Q(('block_reason', ''), _negated=True), _connector='OR'), name='block_requires_reason'),
        ),
        migrations.AddConstraint(
            model_name='tableoccupancy',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), expressions=[('table', '='), (apps.reservations.models.TsTzRange('starts_at', 'ends_at'), '&&')], name='occupancy_no_overlap'),
        ),
    ]
