# Generated by Django 5.2.12 on 2026-10-07 22:29

from django.db import migrations, models

ORIGENES_RETIRADOS = ["staff", "walk_in"]


def a_recepcion(apps, schema_editor):
    Reservation = apps.get_model("reservations", "Reservation")
    Reservation.objects.filter(source__in=ORIGENES_RETIRADOS).update(source="recepcion")


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('phone', 'Teléfono'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('recepcion', 'Recepción')], default='web', max_length=12, verbose_name='origen'),
        ),
        # Irreversible a proposito: no se sabe cual de los dos origenes tenia cada una.
        migrations.RunPython(a_recepcion, migrations.RunPython.noop),
    ]
