sonar.projectKey=Zisa-Reservaciones
sonar.sources=.
sonar.exclusions=venv/**,staticfiles/**,.scannerwork/**,htmlcov/**,**/tests.py,**/tests/**
sonar.tests=apps,wapp
sonar.test.inclusions=**/tests.py,**/tests/**
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests.py,**/tests/**,**/migrations/**,wapp/settings.py,wapp/wsgi.py,wapp/asgi.py,manage.py
