# Generated by Django 5.2.12 on 2026-08-25 01:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='nombre')),
                ('kind', models.CharField(choices=[('allergy', 'Alergia o dieta'), ('preference', 'Preferencia'), ('profile', 'Perfil')], max_length=12, verbose_name='tipo')),
                ('color', models.CharField(default='#6B7280', help_text='Color de la etiqueta en el panel, en hexadecimal.', max_length=7, verbose_name='color')),
                ('show_in_kitchen', models.BooleanField(default=False, help_text='Márcalo en alergias y dietas: así aparece en la comanda que ve la cocina.', verbose_name='visible en cocina')),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('phone', models.CharField(db_index=True, help_text='Escríbelo como quieras: con espacios, guiones o sin el código de país. Se guarda siempre igual (+51987654321).', max_length=20, unique=True, verbose_name='teléfono')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('language', models.CharField(default='es', max_length=5, verbose_name='idioma')),
                ('marketing_opt_in', models.BooleanField(default=False, verbose_name='acepta marketing')),
                ('notes', models.TextField(blank=True, help_text='Solo lo ve el equipo. Nunca se envía al cliente.', verbose_name='notas internas')),
                ('visits', models.PositiveIntegerField(default=0, editable=False, verbose_name='visitas')),
                ('no_shows', models.PositiveIntegerField(default=0, editable=False, verbose_name='no-shows')),
                ('cancellations', models.PositiveIntegerField(default=0, editable=False, verbose_name='cancelaciones')),
                ('last_visit', models.DateField(blank=True, editable=False, null=True, verbose_name='última visita')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('tags', models.ManyToManyField(blank=True, related_name='guests', to='guests.tag', verbose_name='etiquetas')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='guests_gues_name_917223_idx')],
            },
        ),
    ]
