# Generated by Django 5.2.12 on 2026-08-25 01:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('is_bookable', models.BooleanField(default=True, help_text='Desmárcalo en la barra o en zonas que se llenan solo con gente que llega sin reservar.', verbose_name='reservable')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'zona',
                'verbose_name_plural': 'zonas',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('timezone', models.CharField(default='America/Lima', max_length=50, verbose_name='zona horaria')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'restaurante',
                'verbose_name_plural': 'restaurantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(help_text='Como la llama el equipo: S1, T4, B2...', max_length=10, verbose_name='código')),
                ('min_seats', models.PositiveSmallIntegerField(default=1, verbose_name='capacidad minima')),
                ('max_seats', models.PositiveSmallIntegerField(verbose_name='capacidad maxima')),
                ('is_combinable', models.BooleanField(default=True, help_text='Se puede juntar con otras mesas para atender grupos grandes.', verbose_name='combinable')),
                ('pos_x', models.DecimalField(decimal_places=2, default=0, help_text='Dónde está la mesa de izquierda (0) a derecha (100). Solo hace falta si quieres ver el plano dibujado.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición X')),
                ('pos_y', models.DecimalField(decimal_places=2, default=0, help_text='Dónde está la mesa de arriba (0) a abajo (100).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='posición Y')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='venues.area', verbose_name='zona')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['area__sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TableCombination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(help_text='Cómo la llamas: «S3+S4».', max_length=40, verbose_name='nombre')),
                ('min_seats', models.PositiveSmallIntegerField(default=1, verbose_name='capacidad minima')),
                ('max_seats', models.PositiveSmallIntegerField(verbose_name='capacidad maxima')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('tables', models.ManyToManyField(related_name='combinations', to='venues.table', verbose_name='mesas')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinations', to='venues.venue', verbose_name='restaurante')),
            ],
            options={
                'verbose_name': 'combinación de mesas',
                'verbose_name_plural': 'combinaciones de mesas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('weekdays', models.CharField(default='0,1,2,3,4,5,6', help_text='Números separados por coma. 0 es lunes y 6 es domingo. Ejemplo: 4,5,6 para viernes, sábado y domingo.', max_length=13, verbose_name='dias de la semana')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('end_time', models.TimeField(verbose_name='hora de cierre')),
                ('last_seating', models.TimeField(verbose_name='ultima entrada')),
                ('default_duration_min', models.PositiveSmallIntegerField(default=90, help_text='Cuánto dura una reserva de este turno si ningún tramo de la tabla de duraciones encaja con el grupo.', verbose_name='duración por defecto (min)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='venues.venue', verbose_name='restaurante')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DurationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('min_party', models.PositiveSmallIntegerField(verbose_name='comensales desde')),
                ('max_party', models.PositiveSmallIntegerField(verbose_name='comensales hasta')),
                ('minutes', models.PositiveSmallIntegerField(verbose_name='cuánto ocupan la mesa (min)')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duration_rules', to='venues.venue', verbose_name='restaurante')),
            ],
            options={
                'verbose_name': 'duración por tamaño de grupo',
                'verbose_name_plural': 'duración por tamaño de grupo',
                'ordering': ['min_party'],
            },
        ),
        migrations.CreateModel(
            name='CalendarException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('start_date', models.DateField(verbose_name='desde')),
                ('end_date', models.DateField(verbose_name='hasta')),
                ('kind', models.CharField(choices=[('closed', 'Cerrado'), ('special_hours', 'Horario especial'), ('reduced_capacity', 'Aforo reducido')], max_length=20, verbose_name='tipo')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de cierre')),
                ('max_capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='aforo maximo')),
                ('reason', models.CharField(max_length=120, verbose_name='motivo')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_exceptions', to='venues.venue', verbose_name='restaurante')),
            ],
            options={
                'verbose_name': 'día especial',
                'verbose_name_plural': 'días especiales',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='venues.venue', verbose_name='restaurante'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(fields=('area', 'code'), name='unique_table_per_area'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('max_seats__gte', models.F('min_seats'))), name='table_seat_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.CheckConstraint(condition=models.Q(('min_seats__gt', 0)), name='table_min_seats_positive'),
        ),
        migrations.AddConstraint(
            model_name='tablecombination',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_combination_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_shift_per_venue'),
        ),
        migrations.AddConstraint(
            model_name='durationrule',
            constraint=models.CheckConstraint(condition=models.Q(('max_party__gte', models.F('min_party'))), name='duration_rule_range_valid'),
        ),
        migrations.AddIndex(
            model_name='calendarexception',
            index=models.Index(fields=['venue', 'start_date', 'end_date'], name='venues_cale_venue_i_8f11d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarexception',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='calendar_exception_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_area_per_venue'),
        ),
    ]
