# Generated by Django 5.2.12 on 2026-08-25 01:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('channel', models.CharField(choices=[('email', 'Correo'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10, verbose_name='canal')),
                ('template', models.CharField(choices=[('confirmation', 'Confirmación de reserva'), ('reminder_24h', 'Recordatorio 24 h antes'), ('cancellation', 'Cancelación'), ('table_released', 'Aviso de lista de espera'), ('deposit_request', 'Solicitud de depósito')], max_length=30, verbose_name='plantilla')),
                ('recipient', models.CharField(help_text='Teléfono o correo al que se envió.', max_length=120, verbose_name='destino')),
                ('send_status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviada'), ('delivered', 'Entregada'), ('failed', 'Fallida')], default='pending', max_length=10, verbose_name='estado del envío')),
                ('provider_id', models.CharField(blank=True, max_length=80, verbose_name='id del proveedor')),
                ('error', models.TextField(blank=True, verbose_name='error')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='intentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada en')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservation', verbose_name='reserva')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', 'template'], name='notificatio_reserva_bc8bab_idx')],
                'constraints': [models.UniqueConstraint(fields=('reservation', 'template'), name='one_notification_per_template')],
            },
        ),
    ]
